# Generated by Django 5.1.4 on 2024-12-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_rename_response_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Response',
        ),
    ]
